name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug SSH_HOST
      run: |
        echo "SSH_HOST is ${{ vars.SSH_HOST }}"
        echo "SSH_PORT is ${{ vars.SSH_PORT }}"
        echo "SSH_USER is ${{ vars.SSH_USER }}"
        echo "SSH_PATH is ${{ vars.SSH_PATH }}"

    - name: Start SSH agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

    - name: Set up known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
  
    - name: Deploy to cPanel
      env:
        SSH_PORT: ${{ vars.SSH_PORT }}
        SSH_USER: ${{ vars.SSH_USER }}
        SSH_HOST: ${{ vars.SSH_HOST }}
        SSH_PATH: ${{ vars.SSH_PATH }}
      run: |
        bash deploy_script.sh
