name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug SSH_HOST
      run: echo "SSH_HOST is ${{ env.SSH_HOST }}"

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to cPanel
      env:
        SSH_PORT: ${{ env.SSH_PORT }}
        SSH_USER: ${{ env.SSH_USER }}
        SSH_HOST: ${{ env.SSH_HOST }}
        SSH_PATH: ${{ env.SSH_PATH }}
      run: |
        bash deploy_script.sh
