name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug SSH_HOST
      run: |
        echo "SSH_HOST is ${{ vars.SSH_HOST }}"
        echo "SSH_PORT is ${{ vars.SSH_PORT }}"
        echo "SSH_USER is ${{ vars.SSH_USER }}"
        echo "SSH_PATH is ${{ vars.SSH_PATH }}"

    - name: Start SSH agent and add key
      run:  |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.DEPLOY_KEY }}" > id_rsa
        chmod 600 id_rsa
        ssh-add id_rsa

    - name: Set up known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ vars.SSH_PORT }} -t rsa ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-rsa -i id_rsa -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "echo 'SSH connection successful'"
      
  
    - name: Run script on GitHub Actions runner to deploy to cPanel
      env:
        SSH_PORT: ${{ vars.SSH_PORT }}
        SSH_USER: ${{ vars.SSH_USER }}
        SSH_HOST: ${{ vars.SSH_HOST }}
        SSH_PATH: ${{ vars.SSH_PATH }}
      run: |
        bash deploy_script.sh
      
